### ISSUE TITLE
Submit Course Preferences - account for different lecturers

### ISSUE THREAD

**Issue by NinaJhaveri** [USC-CSSL/Automatic-TA-assignment#16]
Current list allows user to submit one preference rating for one course. Eg PSYC 274. 

274 has multiple lecture courses taught in total by 5 different instructors. JoAnn most frequently receives demands to for students to continue TAing with the same instructors (eg Walsh). 

In this E.g., edit the list to be: 
PSYC 274 Lecture code: 52450
PSYC 274 Lecture code: 52455
PSYC 274 Lecture code: 52470
PSYC 274 Lecture code: 52478
PSYC 274 Lecture code: 52475
PSYC 274 Lecture code: 52487

**Comment by mdehghanim** [comment]
This needs to be addressed in this version.

**Comment by mdehghanim** [comment]
I don't think this has been resolved

**Comment by srinidhinandakumar** [comment]
The issue here mentions that user preferences need to be with course-code and sections. That has been achieved. If this needs to be done elsewhere too, please let me know.
![screenshot from 2017-12-10 22 17 06](https://user-images.githubusercontent.com/12572165/33818089-e0ab11bc-ddf7-11e7-8275-5c2678992531.png)

**Comment by mdehghanim** [comment]
This only needs to be addressed where we ask the user is he/she is happy with the previous course TA'ed. That's where we need to get the section number or the name of the professor who taught that course so that if the TA is unhappy with that professor, then he/she should be less likely to be assigned to that professor

**Comment by srinidhinandakumar** [comment]
Okay, got it. So does this need to be kept here too, or should I remove it?

**Comment by mdehghanim** [comment]
You can remove it. Thanks

**Comment by NinaJhaveri** [comment]
Sorry to interject - we need to keep it in both places, so the student can also rank the course preferences differentially for different instructors.

**Comment by mdehghanim** [comment]
No, let's remove it from its current place for now. How does being a TA for this class before address your point?

**Comment by NinaJhaveri** [comment]
Ok, by "current place" I thought it meant the one below that Srinidhi sent a screenshot of. That was the one I referred to that should be kept. Sorry for any confusion. 

![image](https://user-images.githubusercontent.com/34341299/33818360-4b98df76-ddf9-11e7-8865-82481755bdd1.png)
