### ISSUE TITLE
Time constraints need to include all hours 8am-8pm

### ISSUE THREAD

**Issue by NinaJhaveri** [USC-CSSL/Automatic-TA-assignment#22]
Time constraints need to include options for all hours of the day (eg Mon 8-9, Mon 9-10, Mon 10-11). Do not group days (e.g. do not group M and W). 
Please include options for Mon to Fri 8am to 8pm.

**Comment by srinidhinandakumar** [comment]
I have written code to consider only those times when the sections are active because each TA needs to be available for only those times. I thought that it is only relevant if the TA is unavailable during any of the time slots for the sections. That's why when sections are added, the Time Intervals table is populated with section times and TA selects from these times.
Please let me know if what you mentioned needs to be done, because if so, it will affect the database and the matching algorithm.

**Comment by NinaJhaveri** [comment]
Understood, thanks. It’s needed because it holds significant weight in the priority ranking we assign individual students in the algorithm. Not having all available times throws off the ranking.

 

Since this would impact already collected data, I defer to Morteza. He mentioned this issue may need to be resolved in the next iteration.

**Comment by mdehghanim** [comment]
Yes, please resolve this for the next iteration.

**Comment by srinidhinandakumar** [comment]
Okay, will resolve this as an enhancement.
